### ISSUE TITLE
How to use MutateGetVirtual?

### ISSUE THREAD

**Issue by olljanat** [loft-sh/vcluster-sdk#23]
On [v0.9.1-beta.0](https://github.com/loft-sh/vcluster/releases/tag/v0.9.1-beta.0) `MutateCreateVirtual` looks to be working now but as far I see `MutateGetVirtual` still does not works (or I probably don't understand how to use it correctly).

You can find my test plugin from https://github.com/k8s4u/vcluster-sealed-secrets-plugin

When I create secret this message gets logged to syncer log:
```
I0607 20:11:45.909809       1 client.go:269] mutate: calling plugin sealed-secrets to mutate object v1 Secret
```

it does not happen when I get secret and it content is not encrypted like expected.

Is this bug or just incorrect way to use `MutateGetVirtual` ?

**Comment by FabianKramm** [comment]
@olljanat thanks for the issue! `MutateGetVirtual` and `MutateGetPhysical` are currently special cases where you can change the way vcluster would see them internally, essentially it overrides the internal client vcluster uses to retrieve objects. This can make sense if you want to avoid vcluster to resync an object because of changes that vcluster has discovered between the virtual version and physical version. It is not a function to mutate an outgoing object retrieved from the virtual cluster.

**Comment by olljanat** [comment]
ah ok, so it means also that `MutateCreateVirtual` gets only called if vcluster create object?

I some way though that these would be working similarly than `MutatingWebhookConfiguration` with only exception that also Get can be mutated.
